name: environment_setup
description: A command-line application for setting up flutter environment.
version: 1.0.0
repository: https://github.com/ThiagoEvoa/environment_setup

environment:
  sdk: ^3.0.0

dependencies:
  process_run: ^0.13.0
  path: ^1.8.3
  http: ^0.13.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
